# Generated by Django 5.0.1 on 2024-01-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooklistAPI', '0003_category_bookitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
